#!/usr/bin/env node
/* Copy the landing page's third-party libraries and webfonts out of
 * node_modules and into the site, so nothing is fetched from someone else's
 * server at runtime.
 *
 * The project's rule is that everything ships from our own origin — the game
 * has always obeyed it, but the landing page was pulling PixiJS and GSAP from
 * cdnjs and four font families from Google. A blocked or slow CDN turned the
 * hero into a black rectangle and the type into a flash of fallback serif, and
 * it handed a third party a log line for every visitor.
 *
 * Versions are pinned in package.json; this script only moves bytes. Run it
 * after bumping either dependency:
 *   node tools/vendor-sync.mjs
 */
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const NM = path.join(ROOT, 'node_modules');
const VENDOR = path.join(ROOT, 'site', 'js', 'vendor');
const FONTS = path.join(ROOT, 'site', 'fonts');

fs.mkdirSync(VENDOR, { recursive: true });
fs.mkdirSync(FONTS, { recursive: true });

const LIBS = [
  ['pixi.js/dist/pixi.min.js', 'pixi.min.js'],
  ['gsap/dist/gsap.min.js', 'gsap.min.js'],
  ['gsap/dist/ScrollTrigger.min.js', 'ScrollTrigger.min.js'],
];

/* Only the faces the page actually asks for, and only latin. Fontsource ships
 * every weight and subset of each family; copying the lot would be ~40 files
 * for the four we use. */
const FACES = [
  // [package, file, family, weight, style]
  ['im-fell-english-sc', 'im-fell-english-sc-latin-400-normal.woff2', 'IM Fell English SC', 400, 'normal'],
  ['im-fell-english', 'im-fell-english-latin-400-normal.woff2', 'IM Fell English', 400, 'normal'],
  ['im-fell-english', 'im-fell-english-latin-400-italic.woff2', 'IM Fell English', 400, 'italic'],
  ['alegreya-sans', 'alegreya-sans-latin-400-normal.woff2', 'Alegreya Sans', 400, 'normal'],
  ['alegreya-sans', 'alegreya-sans-latin-400-italic.woff2', 'Alegreya Sans', 400, 'italic'],
  ['alegreya-sans', 'alegreya-sans-latin-500-normal.woff2', 'Alegreya Sans', 500, 'normal'],
  ['alegreya-sans', 'alegreya-sans-latin-700-normal.woff2', 'Alegreya Sans', 700, 'normal'],
  ['ibm-plex-mono', 'ibm-plex-mono-latin-400-normal.woff2', 'IBM Plex Mono', 400, 'normal'],
  ['ibm-plex-mono', 'ibm-plex-mono-latin-500-normal.woff2', 'IBM Plex Mono', 500, 'normal'],
];

let bytes = 0;
const copy = (from, to) => {
  if (!fs.existsSync(from)) throw new Error(`missing ${path.relative(ROOT, from)} — run npm install`);
  fs.copyFileSync(from, to);
  bytes += fs.statSync(to).size;
  console.log(`  ${path.relative(ROOT, to)}  ${(fs.statSync(to).size / 1024).toFixed(0)}KB`);
};

console.log('libraries:');
for (const [src, name] of LIBS) copy(path.join(NM, src), path.join(VENDOR, name));

console.log('fonts:');
for (const [pkg, file] of FACES) copy(path.join(NM, '@fontsource', pkg, 'files', file), path.join(FONTS, file));

/* font-display:swap keeps the text readable while the face loads, exactly as
   the Google stylesheet did with &display=swap. */
const css = ['/* Generated by tools/vendor-sync.mjs — do not edit by hand. */']
  .concat(FACES.map(([, file, family, weight, style]) => (
    `@font-face{font-family:'${family}';font-style:${style};font-weight:${weight};` +
    `font-display:swap;src:url('/fonts/${file}') format('woff2');}`
  )))
  .join('\n') + '\n';
fs.writeFileSync(path.join(ROOT, 'site', 'css', 'fonts.css'), css);
console.log(`\nwrote site/css/fonts.css (${FACES.length} faces) — ${(bytes / 1024).toFixed(0)}KB vendored total`);
